name: Render Short

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "URL to background video"
        required: true
      audio_url:
        description: "URL to voice mp3"
        required: true
      srt_url:
        description: "URL to subtitles srt"
        required: true
      title:
        description: "Video title (optional)"
        required: false

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Download assets
        run: |
          echo "Downloading video..."
          curl -L "${{ github.event.inputs.video_url }}" -o video.mp4
          echo "Downloading audio..."
          curl -L "${{ github.event.inputs.audio_url }}" -o audio.mp3
          echo "Downloading subtitles..."
          curl -L "${{ github.event.inputs.srt_url }}" -o subtitles.srt

      - name: Render final short
        run: |
          ls -lh
          ffmpeg -y \
            -i video.mp4 \
            -i audio.mp3 \
            -vf "scale=1080:-2, crop=1080:1920,subtitles=subtitles.srt" \
            -map 0:v -map 1:a \
            -shortest \
            -c:v libx264 -preset veryfast -crf 23 \
            -c:a aac \
            output.mp4

      - name: Upload final video artifact
        uses: actions/upload-artifact@v4
        with:
          name: final-short
          path: output.mp4
